### ISSUE TITLE
onError:Unable to resolve host "alensw.com": No address associated with hostname

### ISSUE THREAD

**Issue by lpslpsl** [Tamicer/Novate#11]
比如我从快图浏览器下载apk ，onError:Unable to resolve host "alensw.com": No address associated with hostname，好像手机上没问题。但是模拟器报这个

**Comment by Tamicer** [comment]
模拟器地址不一样的 host

**Comment by lpslpsl** [comment]
汗，没改过代码的，今天又可以了。先这样吧。不过我感觉也不是模拟器地址什么的原因吧
