### ISSUE TITLE
生命周期问题

### ISSUE THREAD

**Issue by Loofer** [Tamicer/Novate#12]
请问没有考虑到过不绑定生命周期出现内存泄露的问题么，还有okhttp默认是不支持post缓存的。

**Comment by Tamicer** [comment]
@Loofer 后期会了考虑支持rxJava2.x的

**Comment by Loofer** [comment]
这跟rx2.0有什么关系？ 背压就能解决这问题？

**Comment by Tamicer** [comment]
@Loofer 用applictionContext
