### ISSUE TITLE
你好遇到一个问题，没有回调Onnext方法

### ISSUE THREAD

**Issue by lpslpsl** [Tamicer/Novate#15]
偶尔会出现 用fidder和Okhttp的HttpLoggingInterceptor抓包都发现是和服务器正常通信的，但是onext和onerror等都未被调用。onstart是走了的，也只是执行了onstart

**Comment by Tamicer** [comment]
@lpslpsl 有错误log吗

**Comment by lpslpsl** [comment]
招待原因了mRxApiManager用这个管理的时候在第二个Activity里面请求的网络请求，然后第一个activity走了Ondetroy会取消掉之前的请求所以

**Comment by Tamicer** [comment]
@lpslpsl 可以通过tag取消

**Comment by lpslpsl** [comment]
是的。我之前直接调用了cancllAll了。。。。

**Comment by Tamicer** [comment]
@lpslpsl cancel(tag)

**Comment by lpslpsl** [comment]
不过我觉得你这个api管理还是有点问题。比如在一个activity请求多个接口。往map   put进去，第二个会覆盖掉第一个tag的吧。然后你cancle这些方法也没有调用unsubscribe去cancle掉okhttp的请求啊

**Comment by Tamicer** [comment]
@你指同一个key 重复请求多次？

**Comment by lpslpsl** [comment]
是的。这个tag一般都是传this进去吧
