### ISSUE TITLE
下载文件时文件夹DownLoads文件夹创建不成功导致无法下载 具体看下面的类！！！！！

### ISSUE THREAD

**Issue by NBInfo** [Tamicer/Novate#19]
NovateDownLoadManager 类里 
第100行   ：if (path == null) {
                    path = context.getExternalFilesDir(null) + File.separator +"DownLoads" + File.separator;
                    }
修改为：
if (path == null) {
            File filepath=new File(path = context.getExternalFilesDir(null) + File.separator +"DownLoads");
            if (!filepath.exists()){
                filepath.mkdirs();
            }
            path = context.getExternalFilesDir(null) + File.separator +"DownLoads" + File.separator;
        }

**Comment by Tamicer** [comment]
@NBInfo 感谢矫正 赞赞

**Comment by jiezigg** [comment]
我也遇到了，求更新，不想修改源码...

**Comment by jiezigg** [comment]
而且还有个问题哦，就是如何发生这种情况，onEorror里e.getMessage为null，错误信息没能传出来，原因是你的Throwable类里message没有赋值啊

**Comment by Tamicer** [comment]
@jiezigg 具体那一段代码呢

**Comment by Tamicer** [comment]
@jiezigg 更新到了V 1.3.0
