### ISSUE TITLE
对于Retrofit2解析数组

### ISSUE THREAD

**Issue by gukandanmobile** [Tamicer/Novate#25]
就是我之的数据{
    "code": 1200,
    "message": "数据获取成功",
    "data": {
        "curPage": 1,
        "pageSize": 10,
        "list": [
            {
                "product_id": "152",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "人参",
                "price": "￥5.00",
                "special": "暂无特价",
                "allSales": 9
            },
            {
                "product_id": "161",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "刺五加",
                "price": "￥10.00",
                "special": "暂无特价",
                "allSales": 5
            },
            {
                "product_id": "86",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "木贼",
                "price": "￥17.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "139",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "木蝴蝶",
                "price": "￥15.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "191",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "龙眼肉",
                "price": "￥15.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "219",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "柏子仁",
                "price": "￥11.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "220",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "远志",
                "price": "￥13.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "222",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "首乌藤",
                "price": "￥20.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "223",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "灵芝",
                "price": "￥50.00",
                "special": "暂无特价",
                "allSales": 0
            },
            {
                "product_id": "319",
                "image": "http://www.cnyouyao.com/image/cache/placeholder-270x340.png",
                "name": "木香",
                "price": "￥21.00",
                "special": "暂无特价",
                "allSales": 0
            }
        ]
    }
}
就是这种类型解析的时候总是报java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $异常求解决！

**Comment by Tamicer** [comment]
@gukandanmobile 建议不要用原生的 Retrofit ,novate欢迎你
