### ISSUE TITLE
问下为什么使用Novate下载文件的时候

### ISSUE THREAD

**Issue by 921668753** [Tamicer/Novate#27]
问下为什么使用Novate下载文件的时候，用DownLoadCallBack方法，点击下载后，会经过一段时间后才开始有进度显示，为什么啊！是我写的不对吗！求指教
 DownLoadCallBack downLoadCallBack = new DownLoadCallBack() {
            @Override
            public void onError(Throwable e) {
                NovateRestponse.doFailure(e.getCode(), e.getMessage(), listener);
            }

            @Override
            public void onProgress(String key, int progress, long fileSizeDownloaded, long totalSize) {
                super.onProgress(key, progress, fileSizeDownloaded, totalSize);
               showLoadingDialog( progress+"%");
            }

            @Override
            public void onSucess(String key, String path, String name, long fileSize) {
                listener.onSuccess(path);
            }
        };
        Map<String, Object> headers = requestHeader();
  
   new Novate.Builder(KJActivityStack.create().topActivity())
                    //  .addHeader(headers) //添加公共请求头
                    //   .addParameters(parameters)//公共参数
                    .connectTimeout(120)  //连接时间 可以忽略
                    .writeTimeout(100)
                    .addCookie(false)  //是否同步cooike 默认不同步
                    .addCache(isCache)  //是否缓存 默认缓存
                    //    .addCache(new Cache(FileUtils.getSaveFolder(StringConstants.CACHEPATH), StringConstants.CACHE_SIZE)) //自定义缓存
                    .baseUrl(baseUrl) //base URL
                    .addLog(true); //是否开启log
.addHeader(headers)
.build()
.download(null,updateAppUrl,FileUtils.getSaveFolder(StringConstants.DOWNLOADPATH).getAbsolutePath() + "/",, + "a.apk", downLoadCallBack);

**Comment by Tamicer** [comment]
@921668753 哪本版本？

**Comment by 921668753** [comment]
最新版1.5.2.3

**Comment by Tamicer** [comment]
@921668753 来个地址

**Comment by 921668753** [comment]
https://github.com/Tamicer/Novate  什么地址是这个嘛?

**Comment by Tamicer** [comment]
@921668753 我指的你文件下载地址

**Comment by 921668753** [comment]
http://opmnz562z.bkt.clouddn.com/17a4a30ee3db2687a13b599d77f64e3b.apk

**Comment by Tamicer** [comment]
@921668753 进测试 这个地址估计Dns解析 过程耗时，你可以copy到浏览器下载，也需要很久才开始下载，建议你的后端合理部署服务器带块，Dns, 网络拓扑等

**Comment by 921668753** [comment]
好的！谢谢！

**Comment by Tamicer** [comment]
@921668753 您好 经过排查，发现并不是你的url问题，而是retrofit下载的读流的时候就直接返回成功response，时候会修复。
