### ISSUE TITLE
这个是要服务端接收map是吧？

### ISSUE THREAD

**Issue by AbrahamCaiJin** [Tamicer/Novate#32]
这个是要服务端接收map是吧？

**Comment by Tamicer** [comment]
@AbrahamCaiJin 没太明白你的意思

**Comment by AbrahamCaiJin** [comment]
![image](https://user-images.githubusercontent.com/15973675/28512269-c7c79c88-7083-11e7-9354-274923a9f70c.png)
这个是向服务器传map吧？所以服务器接收参数都是接收map吗？

**Comment by Tamicer** [comment]
不是map， 就是普通的字段，客户端为了组装方便用了Map做容器，服务端直接是 一个个取
