### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected char 0x82cf at 0 in a value 中文

### ISSUE THREAD

**Issue by Aniderr** [Tamicer/Novate#33]
请问我在new novate的时候addParameters时候会出现如标题所示的错误，这个怎么解决啊？

**Comment by Tamicer** [comment]
你是怎么调用的

**Comment by Tamicer** [comment]
你是怎么调用的

**Comment by Aniderr** [comment]
就是new novate的时候addParameters，这个Parameters的key-value中的value是中文，就报这个错误。

**Comment by Aniderr** [comment]
@Tamicer 请问如何解决new novate的时候addParameters，这个Parameters的key-value中的value是中文，就报这个错误。

**Comment by Tamicer** [comment]
@Aniderr 我排查下

**Comment by Tamicer** [comment]
@Aniderr 已修复 1.5.4.3版本
