### ISSUE TITLE
类型转换出错Application cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by hrandroid** [Tamicer/Novate#4]
无网络时，缓存拦截器(CaheInterceptor)报错
_**((Activity) context)**_.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(context, R.string.load_cache, Toast.LENGTH_SHORT).show();
                }
            });

原因：由于mContext在Builder的build()中被转为Application
/** set Context. */
mContext = context.getApplicationContext();
导致Novate在addCache时new CaheInterceptor(mContext, cacheControlValue);传入了Application报错

**Comment by NeglectedByBoss** [comment]
你可以先用前一个版本 本地我还在新增新功能

**Comment by NeglectedByBoss** [comment]
用1.2.2版本
