### ISSUE TITLE
Post无法传递中文参数到后台

### ISSUE THREAD

**Issue by dhhuanghui** [Tamicer/Novate#40]

**Comment by Tamicer** [comment]
用最新版本

**Comment by Tamicer** [comment]
用最新版本

**Comment by Tamicer** [comment]
用最新版本

**Comment by dhhuanghui** [comment]
是1.5.4.3版本？改成这个版本以后，原来文件上传都要改了，然后原先写好的post登录都没办法登录了，用1.5.2.3版本就只有post中文的问题

**Comment by dhhuanghui** [comment]
我使用1.5.4.2版本也是一样，中文被novate拦截了好像，错误是
/Novate: Unexpected char 0x6d4b at 0 in name value: 测试题
/Novate: Unexpected char 0x6d4b at 0 in name value: 测试题
/Novate: --> e instanceof Throwable
/Novate: --> java.lang.IllegalArgumentException: Unexpected char 0x6d4b at 0 in name value: 测试题

**Comment by Tamicer** [comment]
1.5.2.3确实有这个问题
