### ISSUE TITLE
GET方法如果maps传递了参数，后台会当成POST

### ISSUE THREAD

**Issue by BestMafen** [Tamicer/Novate#41]
Map<String, Object> map = new HashMap<>();
        map.put("user_name", "aa");
        map.put("password", "xiaokai");
        map.put("nick_name", "xiaokai");
        new Novate.Builder(this)
                .baseUrl("http://192.168.0.110/api/")
                .build()
                .rxGet("user/register/", map, new RxStringCallback() {

请求到后台时，map里有数据，会是POST；map没有数据，才是GET

**Comment by Tamicer** [comment]
好的 收到

**Comment by Tamicer** [comment]
@BestMafen 用最新版本1.5.4.5
