### ISSUE TITLE
添加网络拦截器,提示HTTP 400

### ISSUE THREAD

**Issue by Deepblue1996** [Tamicer/Novate#43]
public class LoggingInterceptor implements Interceptor {

    @Override
    public Response intercept(Chain chain) throws IOException {

        Request orgRequest = chain.request();

        if (orgRequest.method().equals("POST")) {
            RequestBody body = orgRequest.body();

            if (body instanceof FormBody) {
                FormBody.Builder bodyBuilder = new FormBody.Builder();
                FormBody formBody = (FormBody) body;

                //把原来的参数添加到新的构造器，（因为没找到直接添加，所以就new新的）
                for (int i = 0; i < formBody.size(); i++) {
                    bodyBuilder.addEncoded(formBody.encodedName(i), formBody.encodedValue(i));
                }

                formBody = bodyBuilder
                        .addEncoded("token", EasyShopApplication.getInstance().mUser.getToken())
                        .build();

                orgRequest = orgRequest.newBuilder().post(formBody).build();
            }
        }

        return chain.proceed(orgRequest);
    }

}

**Comment by Tamicer** [comment]
@Deepblue1996 400看你后端情况 是否收到

**Comment by Deepblue1996** [comment]
但是我不添加拦截器就正常了,好蛋痛

**Comment by Deepblue1996** [comment]
我知道了, 好像问题出在.addEncoded("token", EasyShopApplication.getInstance().mUser.getToken())

**Comment by Deepblue1996** [comment]
怎么回事,好像参数在接口那里固定死了,一改变,多一个或者少一个都会报400

**Comment by Deepblue1996** [comment]
/**
     * 获取商品列表
     */
    @FormUrlEncoded
    @POST("appgoods/goods_list")
    Observable<NetBase<PageList<GoodInfo>>> getGoodList(@Field("class_id") String classId, @Field("goods_name") String goodsName, @Field("goods_brand_id") String goodsBrandId, @Field("price_desc") Boolean priceDesc,
                                                        @Field("salenum_desc") Boolean salenumDesc, @Field("count_desc") Boolean countDesc,
                                                        @Field("currentPage") String currentPage, @Field("showCount") String showCount);

**Comment by Deepblue1996** [comment]
已解决

**Comment by Tamicer** [comment]
@Deepblue1996 是你后端应该限制的
