### ISSUE TITLE
下载文件时回调依旧很慢

### ISSUE THREAD

**Issue by 921668753** [Tamicer/Novate#45]
String downUrl = "http://imtt.dd.qq.com/16891/D04C035E7C2F3DBCA60A29BCD8C791A8.apk?fsname=com.tencent.mobileqq_7.2.0_730.apk";
        novate.download(downUrl, "test.mei", new DownLoadCallBack() {

            @Override
            public void onStart(String s) {
                super.onStart(s);

                btn_download.setText("DownLoad cancel");
                showPressDialog();
            }

            @Override
            public void onError(Throwable e) {
                Toast.makeText(ExempleActivity.this, "onError:" + e.getMessage(), Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onProgress(String key, int progress, long fileSizeDownloaded, long totalSize) {
                super.onProgress(key, progress, fileSizeDownloaded, totalSize);
                Log.v("test", fileSizeDownloaded + "");
                //Toast.makeText(ExempleActivity.this, "progress: " + progress + "   download: " + fileSizeDownloaded, Toast.LENGTH_SHORT).show();
                updateProgressDialog(progress);

            }

            @Override
            public void onSucess(String key, String path, String name, long fileSize) {
                Toast.makeText(ExempleActivity.this, "download  onSucess", Toast.LENGTH_SHORT).show();
                dismissProgressDialog();
            }

            @Override
            public void onCancel() {
                super.onCancel();
                dismissProgressDialog();
            }

        });
用的是excemple里面的例子只是把下载地址换了一下，发现下载时，进度条不会很长一段时间不会变动

**Comment by Tamicer** [comment]
new Novate.build().rxdown()
