### ISSUE TITLE
如何获取HttpURLConnection以及ResponseCode?

### ISSUE THREAD

**Issue by wyvector** [Tamicer/Novate#46]
您好！
我想请教下，在您的最新框架下，如何获取HttpURLConnection以及ResponseCode?
非常感谢！

**Comment by wyvector** [comment]
再请教一个问题：对于NovateCookieManager的使用，有相应的指导连接么？

**Comment by Tamicer** [comment]
这块是直接有返回的吧

**Comment by Tamicer** [comment]
重写拦截器

**Comment by Tamicer** [comment]
@wyvector 自定义拦截器 可以获取原生的Code
