### ISSUE TITLE
在1.2.41版本中我发现同时用了Gosn和FastJson,okhttpBuilder.sslSocketFactory过时

### ISSUE THREAD

**Issue by ileixiao** [Tamicer/Novate#5]
首先感谢您的封装，让我可以简单使用Retrofit+Rxjava!
我查看您的源码
发现1.2.41版本Novate中的onNext()方法中存在了俩个解析框架（Gosn和FastJson），应该是您忘记完全替换了。
还有okhttpBuilder.sslSocketFactory(sslSocketFactory);在okhttp3.4.2中已过时，应该用什么替换呢？

**Comment by Tamicer** [comment]
用1.2.6.1, 实现了全T泛型，过时这个暂时还没关系，等我在研究下最新的方式。
