### ISSUE TITLE
请问下返回bean怎么使用 ,,,,

### ISSUE THREAD

**Issue by hackgyc** [Tamicer/Novate#51]
返回Bean

 novate.rxPost("http://xxxxxxx/login/xxxx", parameters, object : RxResultCallback<LoginBean>() {
                override fun onCancel(tag: Any?, e: Throwable?) {

                }

                override fun onStart(tag: Any?) {
                    super.onStart(tag)
                }

                override fun onNext(tag: Any?, call: Call?, response: LoginBean?) {
                    super.onNext(tag, call, response)
                    Log.e("TAG", call.toString()+"登录返回--->" + response?.data?.name)
                }

                override fun onNext(tag: Any?, code: Int, message: String?, response: LoginBean?) {
                    Log.e("TAG", call.toString()+"登录返回--->" + response?.data?.name)
                }

                override fun onError(tag: Any?, e: Throwable?) {

                }

            })
我这样用了，onNext里的bean都是null、字串实体类都对应的，不知道什么情况

**Comment by Tamicer** [comment]
@hackgyc 你的后端数据 是否符合： {code msg data}格式

**Comment by hackgyc** [comment]
@Tamicer 后面发现了，，就是后端数据格式不致

**Comment by Tamicer** [comment]
@hackgyc 可以参考wiki中的 https://github.com/Tamicer/Novate/wiki/RxCallBack 。**RxGenericsCallback**回调对原始数据进行处理

**Comment by hackgyc** [comment]
@Tamicer OK  好的，  谢谢
