### ISSUE TITLE
类型转换出错

### ISSUE THREAD

**Issue by Huwei1993** [Tamicer/Novate#61]
回调：RxResultCallback<ApiResult<VerifyBean>>
ApiResult  是：
    private int code;
    private String message;
    private String msg;
    private T data;
会报类型转换错误，可以使用哪个回调方法才不会报错？

**Comment by Huwei1993** [comment]
报错位置：callback.RxGenericsCallback.onHandleResponse(RxGenericsCallback.java:63)
代码： libcore.refType entityClass =((ParameterizedType)foo.getClass().getGenericSuperclass()).getActualTypeArguments()[0];
错误信息：lect.ParameterizedTypeImpl cannot be cast to java.lang.Class

**Comment by Huwei1993** [comment]
是 new RxResultCallback<ApiResult<TvSafeVerifyBean>> 

 Class<T> entityClass = (Class)((ParameterizedType)this.getClass().getGenericSuperclass()).getActualTypeArguments()[0];

转换出错
出错信息：libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class

**Comment by junges521** [comment]
怎么处理呢，这个问题怎么处理

**Comment by Tamicer** [comment]
@junges521 你的数据类型没匹配上：
要满足基本的：

private int code;
private String msg;
private T data;
