### ISSUE TITLE
引入最新版后，APP闪退

### ISSUE THREAD

**Issue by nanbowan555** [Tamicer/Novate#65]
java.lang.NoSuchMethodError: No virtual method callEnqueue(Lokhttp3/Call;Lokhttp3/Callback;Z)V in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in /data/app/com.weclassroom.fcclassroomapp-1/base.apk:classes6.dex)
                                                                                    at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)

**Comment by Tamicer** [comment]
@还有更多的日志吗

**Comment by nanbowan555** [comment]
如果之前项目中引入过socketIO和okhttp，可能会闪退。我将sockedIO和okhttp的版本改了之后，就没有闪退了

**Comment by Tamicer** [comment]
分享下你的改版方式，已帮助更多人

**Comment by nanbowan555** [comment]
https://stackoverflow.com/questions/42209251/okhttp3-java-lang-nosuchmethoderror-no-virtual-method-setcallwebsocket 我是参考这个解决方案的

**Comment by Tamicer** [comment]
你这和本框架没关系了 是包重复问题，来个去除重复引用就行
