### ISSUE TITLE
获取List为空

### ISSUE THREAD

**Issue by zongkang** [Tamicer/Novate#66]
bean:
 GiftCardList {
 private int maxPage;
    private List<GiftCardBean> myEGiftCardList;

    public int getMaxPage() {
        return maxPage;
    }

    public void setMaxPage(int maxPage) {
        this.maxPage = maxPage;
    }

    public List<GiftCardBean> getMyEGiftCardList() {
        return myEGiftCardList;
    }

    public void setMyEGiftCardList(List<GiftCardBean> myEGiftCardList) {
        this.myEGiftCardList = myEGiftCardList;
    }
}

回调：RxResultCallback<GiftCardList >  
返回信息：数组内为空

问题：novate 框架不支持这种的bean传入吗？？

**Comment by Tamicer** [comment]
支持
