### ISSUE TITLE
Error:(29, 13) Failed to resolve: com.tamic.novate:novate:1.5.4.3

### ISSUE THREAD

**Issue by wangsongbin001** [Tamicer/Novate#71]

**Comment by wangsongbin001** [comment]
project:  
  repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
module:
    dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.tamic.novate:novate:1.5.4.3'
}

**Comment by Tamicer** [comment]
试试 compile 'com.tamic.novate:novate:1.5.4.5'
