### ISSUE TITLE
不能使用rxBodyGet（）这个方法，报错，怎么解决？

### ISSUE THREAD

**Issue by Huwei1993** [Tamicer/Novate#75]
Caused by: java.lang.IllegalArgumentException: Non-body HTTP method cannot contain @Body

**Comment by Tamicer** [comment]
贴下代码

**Comment by Huwei1993** [comment]
API.getmNovate().rxBodyGet(urlAPi, parames1, new RxStringCallback() {
            @Override
            public void onNext(Object tag, String response) {
                Toast.makeText(MainActivity.this,response,Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onError(Object tag, Throwable e) {
                Toast.makeText(MainActivity.this,e.getMessage(),Toast.LENGTH_SHORT).show();

            }

            @Override
            public void onCancel(Object tag, Throwable e) {

            }
        });

**Comment by Huwei1993** [comment]
我自己弄错了（<··>）
