### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sweet2o09** [Tamicer/Novate#8]
android:allowBackup="false"的时候无法使用compile引入库文件

**Comment by Tamicer** [comment]
@sweet2o09 你的主工程是android:allowBackup="false的？

**Comment by Tamicer** [comment]
@sweet2o09 你的主工程是android:allowBackup="true"的？

**Comment by sweet2o09** [comment]
不是都应该把主工程设置成android:allowBackup="false"么

**Comment by Tamicer** [comment]
android:allowBackup="true" 目前都是设置为true"的

**Comment by sweet2o09** [comment]
之前设置成true,被阿里跟腾讯的安全检查报是高危漏洞..

**Comment by Tamicer** [comment]
@sweet2o09 我稍后升级下版本，取消这个限制 1.2.8
